# Generated by Django 3.0.5 on 2020-08-05 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200805_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Títuo')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Career', verbose_name='Imagen')),
                ('session', models.CharField(max_length=100, verbose_name='Sesión')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Finalización')),
                ('result', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
