# Generated by Django 3.0.5 on 2020-08-05 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_career_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-created'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carrera'},
        ),
        migrations.AddField(
            model_name='career',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
