# Generated by Django 3.0.5 on 2020-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200805_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo de la Foto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Imagen')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción de la foto')),
            ],
        ),
    ]
