# Generated by Django 3.0.5 on 2020-08-05 19:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200805_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Icono')),
                ('title', models.CharField(max_length=100, verbose_name='Titulos de la elección')),
                ('content', ckeditor.fields.RichTextField(max_length=200, verbose_name='Descripción de la elección')),
            ],
        ),
    ]
