# Generated by Django 3.0.5 on 2020-08-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200806_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='relevance',
            field=models.IntegerField(default=0, verbose_name='Importancia'),
        ),
    ]
