# Generated by Django 3.0.5 on 2020-08-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ability_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team', verbose_name='Imagen team'),
        ),
    ]
