# Generated by Django 3.0.5 on 2020-08-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_project_important_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='important_title',
        ),
    ]
