# Generated by Django 3.0.5 on 2020-08-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200826_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar'),
        ),
    ]
